Add Tried
TestingResearchIllinois/idoft pull request #1117
Opened 2023-11-29 23:16 UTC by MyEnthusiastic

2023-11-30 04:37 UTC, zzjas commented on pr-data.csv
> +https://github.com/apache/activemq,dfd35d89f62558881bda1ed4cf7a165502c5c1035,activemq-mqtt,org.apache.activemq.transport.mqtt.MQTTTest.testMQTTCompositeDestinations,ID,,https://issues.apache.org/jira
Typo in SHA? The format checker is complaining.

2023-11-30 04:37 UTC, zzjas commented on pr-data.csv
> +https://github.com/apache/activemq,dfd35d89f62558881bda1ed4cf7a165502c5c1035,activemq-mqtt,org.apache.activemq.transport.mqtt.MQTTTest.testMQTTCompositeDestinations,ID,,https://issues.apache.org/jira
Also please put the URL in the `Notes` column. If you are able to raise a PR, then please put the PR link in the `PR Link` column.

2023-12-01 04:11 UTC, darko-marinov requested changes
Please add some more justification that the tests are `ID`.

2023-12-01 04:11 UTC, darko-marinov commented on format_checker/forked-projects.json
> -}
Please no unnecessary changes here.

2023-12-01 04:11 UTC, darko-marinov commented on pr-data.csv
> +https://github.com/apache/tez,51d6f53967110e2b91b6d90b46f8e16bdc062080,tez-dag,org.apache.tez.dag.app.dag.impl.TestCommit.testDAGCommitFail1_OnDAGSuccess,ID,,,Symptom : Time limit exceeds
`Time limit exceeds` doesn't sound like `ID`. Did you run the test individually, not in the entire module? Did you run it multiple times? Does it always give the same error for the same seeds?

2023-12-01 04:11 UTC, darko-marinov commented on pr-data.csv
> +https://github.com/apache/activemq,dfd35d89f62558881bda1ed4cf7a165502c5c989,activemq-jaas,org.apache.activemq.jaas.LDAPLoginModuleTest.testAESEncryptedLogin,ID,,,LDAP is kind of common problem
Does the test pass without NonDex?

2023-12-06 06:02 UTC, MyEnthusiastic commented
Because this PR had too much documents to provide, so I decide to close that. :)

2023-12-06 06:02 UTC, closed without merging

2023-12-06 17:08 UTC, zzjas commented
Do you mean you want to separate them into smaller new PRs?

Or do you mean you want to abort reporting these new tests?