Added MovedToGradle for OD-Vic test cases in spring-boot
TestingResearchIllinois/idoft pull request #1441
Opened 2024-11-05 22:22 UTC by hermya

Added MovedToGradle for OD-Vic test cases in spring-boot

2024-11-06 03:20 UTC, darko-marinov requested changes
Need more evidence for the claims.

2024-11-07 16:02 UTC, hermya commented on gr-data.csv
> +https://github.com/spring-projects/spring-boot,daa3d457b71896a758995c264977bdd1414ee4d4,spring-boot-project/spring-boot,org.springframework.boot.context.properties.bind.CollectionBinderTests.bindToSe
I am currently trying to run IdFlakies on the project. There are some problems with running it (gradle with iDFlakies)

2024-11-07 19:10 UTC, darko-marinov commented on gr-data.csv
> +https://github.com/spring-projects/spring-boot,daa3d457b71896a758995c264977bdd1414ee4d4,spring-boot-project/spring-boot,org.springframework.boot.context.properties.bind.CollectionBinderTests.bindToSe
If you can't confirm that the test is `ID` in Gradle, then just mark it `MovedToGradle` in `pr-data.csv` but don't add it in `gr-data.csv`.

2024-11-07 23:04 UTC, hermya commented on gr-data.csv
> +https://github.com/spring-projects/spring-boot,daa3d457b71896a758995c264977bdd1414ee4d4,spring-boot-project/spring-boot,org.springframework.boot.context.properties.bind.CollectionBinderTests.bindToSe
Okay. Currently I removed all changed data from gr-data.csv. Will update in future once verified

2024-11-08 04:17 UTC, merged