Adding new Flaky Test servicecomb-java-chassis
TestingResearchIllinois/idoft pull request #612
Opened 2022-09-01 21:40 UTC by anantdahiya8

2022-09-01 22:14 UTC, darko-marinov requested changes
You should correct the format (and confirm that the checker passes).

2022-09-01 22:14 UTC, darko-marinov commented on pr-data.csv
> +https://github.com/apache/servicecomb-java-chassis,76813bc18a2513d6797794721d0bcf72dcc4ab22,foundations/foundation-vertx,org.apache.servicecomb.foundation.vertx.http.TestAbstractHttpServletRequest#te
The test name format is wrong, should use '.' (not '#') to separate test class name and method name.

2022-09-02 04:59 UTC, darko-marinov requested changes
The checker still fails; wrong sort order (see IDoFT README for more info on sorting).

2022-09-02 05:49 UTC, darko-marinov requested changes
Can you please squash your two commits into one? If it's hard, let me know, and I can do it.

2022-09-02 05:52 UTC, anantdahiya8 commented
> Can you please squash your two commits into one? If it's hard, let me know, and I can do it.

Done

2022-09-02 06:00 UTC, merged