Update Accepted Flaky Tests
TestingResearchIllinois/idoft pull request #631
Opened 2022-11-10 09:02 UTC by BoyuLi4

**Update Accepted tests.**

**For the `https://github.com/alibaba/nacos` I don't remember when this Reject PR came out, but it should not be there at the beginning of the semester.

2022-11-10 19:40 UTC, xieyt2000 commented
LGTM

2022-11-13 17:51 UTC, darko-marinov requested changes
Great work. Just please record previous `Rejected` in notes so we can easier find the cases. These are unusual as people don't bother to revisit something previously rejected.

2022-11-13 17:51 UTC, darko-marinov commented on pr-data.csv
> +https://github.com/alibaba/nacos,a0543adafcfed733c0659454e58b3bcd605008a4,common,com.alibaba.nacos.common.utils.JacksonUtilsTest.testToJson1,ID,Accepted,https://github.com/alibaba/nacos/pull/9340,
Can you please put in `Notes` that it was `Rejected` in that prior PR?

2022-11-13 17:51 UTC, darko-marinov commented on pr-data.csv
> +https://github.com/alibaba/nacos,a0543adafcfed733c0659454e58b3bcd605008a4,common,com.alibaba.nacos.common.utils.JacksonUtilsTest.testToJsonBytes1,ID,Accepted,https://github.com/alibaba/nacos/pull/934
As above, record rejected in notes.

2022-11-14 14:09 UTC, merged