update accepted PRs
TestingResearchIllinois/idoft pull request #672
Opened 2022-11-30 21:23 UTC by yannizhou05

Accepted PRs:

https://github.com/apache/cloudstack/pull/6905

https://github.com/apache/rocketmq-dashboard/pull/120

2022-12-01 01:41 UTC, darko-marinov commented
Please make checker pass, and double check entries along the way.

2022-12-01 04:35 UTC, xieyt2000 requested changes
The checker is currently failing because of a recent Github update, we'll fix soon

2022-12-01 04:35 UTC, xieyt2000 commented on pr-data.csv
> +https://github.com/alibaba/druid,ad05a9293b6be2d5562807698b215b673db0417a,core,com.alibaba.druid.bvt.pool.DruidDataSourceTest_exceptionSorter.test_event_error,ID,MovedOrRenamed,,https://github.com/al
Please don't change the module in this row (keep `pool`) and add a new row with the module as `core` and empty status and note

2022-12-01 04:49 UTC, darko-marinov commented
Please rebase to the latest `main` so that we can run the checker.

2022-12-02 01:22 UTC, darko-marinov commented
The checker passes now. Please address Yuntong's comment about `core` and `pool`.

2022-12-02 02:47 UTC, xieyt2000 approved these changes

2022-12-02 02:47 UTC, yannizhou05 commented
Updated. Thank you!

2022-12-02 03:12 UTC, yannizhou05 commented on pr-data.csv
> +https://github.com/alibaba/druid,ad05a9293b6be2d5562807698b215b673db0417a,core,com.alibaba.druid.bvt.pool.DruidDataSourceTest_exceptionSorter.test_event_error,ID,,,
Sorry that I forgot to update the SHA. Updated now.

2022-12-02 03:21 UTC, merged