Add some new test to pr-data.csv
TestingResearchIllinois/idoft pull request #686
Opened 2022-12-04 21:44 UTC by Kerr0220

I've found 15 new flaky tests in repo [apache/druid](https://github.com/apache/druid) using NonDex. Below is the log of running the NonDex:
Test Name| 933178| 974622| 1016066  
---|---|---|---  
org.apache.druid.storage.aliyun.OssDataSegmentPusherConfigTest#testSerialization|✖| ✖| ✖  
org.apache.druid.storage.aliyun.OssDataSegmentPusherConfigTest#testSerializationWithDefaults|✖| ✖| ✖
org.apache.druid.java.util.emitter.core.ParametrizedUriEmitterTest#testEmitterWithMultipleFeeds|✖| ✖| ✔  
org.apache.druid.java.util.emitter.core.ParametrizedUriEmitterTest#testEmitterWithParametrizedUriExtractor|✖| ✖| ✖  
org.apache.druid.java.util.emitter.core.EmitterTest#testGzipContentEncoding|✖| ✖| ✔  
org.apache.druid.java.util.emitter.core.EmitterTest#testSanityWithGeneralizedCreation|✖| ✔| ✔  
org.apache.druid.java.util.emitter.core.EmitterTest#testSanity| ✖| ✖| ✔  
org.apache.druid.java.util.emitter.core.EmitterTest#testBatchSplitting| ✖| ✖|✖  
org.apache.druid.math.expr.ParserTest#testApplyFunctions| ✖| ✖| ✖  
org.apache.druid.math.expr.ParserTest#testSimpleMultiplicativeOp1| ✖| ✖| ✖  
org.apache.druid.math.expr.ParserTest#testFunctions| ✖| ✖| ✖  
org.apache.druid.math.expr.ParserTest#testSimpleLogicalOps1| ✖| ✖| ✖  
org.apache.druid.math.expr.ParserTest#testSimpleAdditivityOp1| ✖| ✖| ✖  
org.apache.druid.math.expr.ParserTest#testSimpleAdditivityOp2| ✖| ✖| ✖  
org.apache.druid.java.util.emitter.core.EmitterTest#testBasicAuthenticationAndNewlineSeparating|✔| ✔| ✖

2022-12-04 23:48 UTC, xieyt2000 requested changes

2022-12-04 23:48 UTC, xieyt2000 commented on pr-data.csv
> +https://github.com/apache/druid,50963edcae70150f13520b619f167512d951a71b,core,org.apache.druid.java.util.emitter.core.ParametrizedUriEmitterTest.testEmitterWithFeedUriExtractor,ID,,,
This line is different from your log in PR text.
Did you manually enter these 15 tests? Or did you insert the records using some scripts?

2022-12-05 19:40 UTC, xieyt2000 approved these changes
LTGT

2022-12-06 20:17 UTC, darko-marinov commented
Accepting this. Considering the initial difference between the table and the PR, you may want to check to (1) sort tests by name in the table, and (2) add module name in the table.

2022-12-06 20:17 UTC, merged